eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/students/**
        - id: school-service
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/schools/**
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/KreakxX-rest-api